### ISSUE TITLE
NCF 모델 모듈화

### ISSUE THREAD

**Issue by annakong23** [boostcampaitech7/level2-recsys-movierecommendation-recsys-05-lv3#62]
### 배경 및 필요성

모델 간의 통일성을 갖추고 사용자가 코드를 수정하여 실행하지 않도록 합니다.

### 구현 내용

- NCF 모델 모듈화

**Comment by SayOny** [comment]
<img width="1119" alt="스크린샷 2024-12-13 18 37 26" src="https://github.com/user-attachments/assets/7ad2d907-1bf8-455e-acac-5b927afc3ca8" />

main.py에 모델 NCF 추가해서 잘 돌아가는 것을 확인했습니다. 이대로 합치면 될 듯 합니다.

**Comment by SayOny** [comment]
NCF yaml 아웃풋 경로가 잘못되어서 변경했습니다. 
이제 
Recommandataion saved to saved/output/NCF.csv 
으로 될 것입니다.
